"""
Django settings for mysite project.

Generated by 'django-admin startproject' using Django 5.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
from dotenv import load_dotenv
import os

load_dotenv()

OPENAI_API_KEY = os.getenv("OPENAI_API_KEY")

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = [
    'codechecksai.loan',
    'www.codechecksai.loan',
    '43.207.3.184',
    'localhost',
    '127.0.0.1',
]

SITE_ID = 1
DOMAIN = os.environ.get('DOMAIN')
if not DOMAIN:
    raise Exception("DOMAIN environment variable must be set")

SITE_NAME = os.environ.get('SITE_NAME', 'CodeCheckAI')

# Application definition

INSTALLED_APPS = [
    'django_user_agents',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'a_classroom.apps.AClassroomConfig',
    'b_enrollment.apps.BEnrollmentConfig',
    'c_activities.apps.CActivitiesConfig',
    'd_compiler.apps.DCompilerConfig',
    'register.apps.RegisterConfig',
]

TAILWIND_APP_NAME = 'theme'
NPM_BIN_PATH = "/usr/bin/npm"


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django_user_agents.middleware.UserAgentMiddleware',
    # below is the middleware from register app
    'register.middleware.NoCacheMiddleware',
    'register.middleware.RedirectAuthenticatedUserMiddleware',
    # below is the middleware for the whitenoise
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'd_compiler.middleware.RestrictPlaygroundViewMiddleware',
    'a_classroom.middleware.InstructorOnlyMiddleware',
    'a_classroom.middleware.AdminOnlyMiddleware',
    'a_classroom.middleware.A_ClassroomMiddleware',
    'a_classroom.middleware.SuperAdminOnlyMiddleware',
    'a_classroom.middleware.DeanNotAllowedMiddleware',
    # below is middlware for b_enrollment
    'b_enrollment.middleware.B_EnrollmentMiddleware',
    'b_enrollment.middleware.StudentOnlyMiddleware',
    # below is middleware for c_activities
    'c_activities.middleware.InstructorOnlyMiddleware',
]

ROOT_URLCONF = 'mysite.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'mysite.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': os.getenv("DB_NAME"),
        'USER' : os.getenv("DB_USER"),
        'PASSWORD' : os.getenv("DB_PASSWORD"),
        'HOST' : os.getenv("DB_HOST"),
        'PORT' : os.getenv("DB_PORT"),
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Manila'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/
STATIC_URL = '/static/'
STATICFILES_DIRS = [
    BASE_DIR / 'static'
]
STATIC_ROOT = BASE_DIR / "productionfiles"

MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
LOGIN_REDIRECT_URL = '/classroom/'
LOGOUT_REDIRECT_URL = '/login/'
#api key for the compiler
JUDGE0_URL = "https://judge0-ce.p.rapidapi.com/submissions"
HEADERS = {
    "X-RapidAPI-Key": "504f5f8347mshfddb83bb53d2821p1f2430jsne3a1f53c5a1b",
    "X-RapidAPI-Host": "judge0-ce.p.rapidapi.com"
}
#configuration for sending an email
if DEBUG:
    EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
else:
    EMAIL_BACKEND = os.getenv("EMAIL_BACKEND")
    EMAIL_HOST = os.getenv("EMAIL_HOST")
    EMAIL_PORT = os.getenv("EMAIL_PORT")
    EMAIL_USE_TLS = os.getenv("EMAIL_USE_TLS")
    EMAIL_HOST_USER = os.getenv("EMAIL_HOST_USER")
    EMAIL_HOST_PASSWORD = os.getenv("EMAIL_HOST_PASSWORD")
    DEFAULT_FROM_EMAIL = os.getenv("EMAIL_HOST_USER")
#configuration for allowing the user to upload and display an image
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'