# Generated by Django 5.2.6 on 2025-09-15 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('c_activities', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='max_attempt',
            field=models.PositiveIntegerField(blank=True, default=3, null=True),
        ),
    ]
