# Generated by Django 5.2 on 2025-11-06 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('c_activities', '0002_alter_activity_max_attempt'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='language',
            field=models.CharField(default='python', max_length=50),
        ),
    ]
