# Generated by Django 5.2 on 2025-11-11 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('c_activities', '0003_activity_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitysubmission',
            name='score',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
    ]
