# Generated by Django 5.2 on 2025-12-25 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('c_activities', '0004_alter_activitysubmission_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activitysubmission',
            name='attempt',
        ),
    ]
