# Generated by Django 5.2 on 2025-10-06 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b_enrollment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(blank=True, default='mysite_images/logo.png', null=True, upload_to='mysite_images/'),
        ),
    ]
