# Generated by Django 5.2 on 2025-12-22 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b_enrollment', '0002_alter_userprofile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Instructor', 'Instructor'), ('Student', 'Student'), ('Dean', 'Dean')], default='Student', max_length=20),
        ),
    ]
